'use client'

import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowDownRight, ArrowUpRight, Bell, BookOpen, Bot, BrainCircuit,
  BriefcaseBusiness, ChevronLeft, ChevronRight, CircleHelp, Coins, Compass,
  GraduationCap, LayoutDashboard, LineChart, Menu, Moon, MoreHorizontal,
  Play, Plus, Search, Settings, ShieldCheck, Sparkles, Sun, Target, TrendingUp,
  Wallet, Zap
} from 'lucide-react'

const nav = [
  ['Dashboard', LayoutDashboard], ['Markets', LineChart], ['Portfolio', BriefcaseBusiness],
  ['AI Advisor', BrainCircuit], ['Learn', GraduationCap], ['Simulator', Activity],
  ['Strategies', Target], ['Notifications', Bell], ['Settings', Settings],
] as const
function Sparkline({ points, red = false }: { points: string; red?: boolean }) {
  return <svg viewBox="0 0 100 20" preserveAspectRatio="none" className="sparkline" aria-hidden="true"><polyline points={points} fill="none" stroke={red ? 'var(--loss)' : 'var(--primary)'} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>
}
function Chart({ compact = false }: { compact?: boolean }) {
  return <svg viewBox="0 0 640 220" preserveAspectRatio="none" className={compact ? 'chart chart-compact' : 'chart'} aria-label="Portfolio performance chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity=".25" /><stop offset="1" stopColor="var(--primary)" stopOpacity="0" /></linearGradient></defs><path d="M0 180 C38 160 46 170 78 148 S125 142 154 126 S193 144 225 116 S275 125 300 100 S350 112 382 72 S425 98 458 65 S520 78 550 38 S600 50 640 18 L640 220 L0 220Z" fill="url(#area)" /><path d="M0 180 C38 160 46 170 78 148 S125 142 154 126 S193 144 225 116 S275 125 300 100 S350 112 382 72 S425 98 458 65 S520 78 550 38 S600 50 640 18" fill="none" stroke="var(--primary)" strokeWidth="3" strokeLinecap="round" /></svg>
}

function WorkspaceView({ active, currency, money, balance, setBalance, setProgress, progress, stocks }: { active: string; currency: string; money: (value: number) => string; balance: number; setBalance: (value: number) => void; setProgress: (value: number) => void; progress: number; stocks: any[] }) {
  const [tradeQty, setTradeQty] = useState(1)
  const [tradeSymbol, setTradeSymbol] = useState('AAPL')
  const [mentorMessage, setMentorMessage] = useState('')
  const [mentorReply, setMentorReply] = useState('Ask me about risk, entries, or your learning path.')
  const sections: Record<string, { eyebrow: string; title: string; description: string }> = {
    Markets: { eyebrow: 'MARKET INTELLIGENCE', title: 'See the market before it moves.', description: 'Real-time watchlists, momentum signals, and AI-ranked opportunities.' },
    Portfolio: { eyebrow: 'YOUR MONEY', title: 'Portfolio performance, made clear.', description: 'Track allocation, returns, exposure, and the next best action.' },
    'AI Advisor': { eyebrow: 'DECISION INTELLIGENCE', title: 'Your always-on trading co-pilot.', description: 'Translate market context into explainable, risk-aware decisions.' },
    Learn: { eyebrow: 'LEARN WITH EARNING', title: 'Build conviction through practice.', description: 'Follow a guided path from fundamentals to advanced strategy design.' },
    Simulator: { eyebrow: 'PAPER TRADING', title: 'Practice without the pressure.', description: 'Test ideas with virtual cash before putting real capital at risk.' },
    Strategies: { eyebrow: 'STRATEGY LAB', title: 'Compare your edge over time.', description: 'Explore tested playbooks and tune them to your risk profile.' },
    Notifications: { eyebrow: 'SIGNAL CENTER', title: 'The alerts worth your attention.', description: 'Your AI watchtower is monitoring the moments that matter.' },
    Settings: { eyebrow: 'CONTROL CENTER', title: 'Make the workspace yours.', description: 'Manage preferences, notifications, and your investing workflow.' },
  }
  const section = sections[active] ?? sections.Markets
  const submitMentor = () => { if (mentorMessage.trim()) { setMentorReply(`Based on your question, ${mentorMessage.trim().toLowerCase()} is best approached with a defined stop, a clear thesis, and a position size that protects your downside.`); setMentorMessage('') } }
  const trade = (side: 'Buy' | 'Sell') => setBalance(Math.max(0, balance + (side === 'Buy' ? -tradeQty * 189.98 : tradeQty * 189.98)))
  return <div className="workspace-view">
    <div className="workspace-heading"><div><p className="eyebrow">{section.eyebrow}</p><h2>{section.title}</h2><p className="lede">{section.description}</p></div><button className="primary-btn" onClick={() => active === 'Learn' ? setProgress(Math.min(100, progress + 8)) : setBalance(balance + 250)}> {active === 'Learn' ? 'Complete lesson' : 'Take action'} <ArrowUpRight /></button></div>
    {active === 'Markets' && <><div className="workspace-grid two-up">{stocks.map(stock => <div className="card detail-card" key={stock.symbol}><div className="card-head"><span>{stock.symbol} · {stock.name}</span><span className={stock.change < 0 ? 'loss' : 'gain'}>{stock.change > 0 ? '+' : ''}{stock.change}%</span></div><strong className="detail-price">{stock.symbol === 'BTC' ? '$' + stock.price.toLocaleString() : money(stock.price)}</strong><Sparkline points={stock.points} red={stock.change < 0} /><p className="muted-copy">AI momentum is {stock.change > 0 ? 'accelerating' : 'cooling'} with {Math.abs(stock.change * 18).toFixed(0)}% signal confidence.</p></div>)}</div><div className="card table-card"><div className="card-head"><span>AI-ranked opportunities</span><span className="live-status">Live scan</span></div>{stocks.map((stock, index) => <div className="data-row" key={stock.symbol}><strong>{index + 1}</strong><span>{stock.symbol}</span><span>{stock.change > 0 ? 'Momentum breakout' : 'Volatility watch'}</span><b className={stock.change < 0 ? 'loss' : 'gain'}>{stock.change > 0 ? 'Bullish' : 'Cautious'}</b></div>)}</div></>}
    {active === 'Portfolio' && <><div className="workspace-grid three-up"><div className="card metric-card"><span>Net worth</span><strong>{money(balance)}</strong><b className="gain">+7.4% this month</b></div><div className="card metric-card"><span>Invested</span><strong>{money(balance * .72)}</strong><b>72% allocation</b></div><div className="card metric-card"><span>Buying power</span><strong>{money(balance * .28)}</strong><b>Available now</b></div></div><div className="card large-detail"><div className="card-head"><span>Portfolio growth</span><span>1D · 1W · 1M · 1Y</span></div><Chart /></div><div className="workspace-grid two-up"><div className="card table-card"><h3>Holdings</h3>{stocks.slice(0, 3).map(stock => <div className="data-row" key={stock.symbol}><span>{stock.symbol}</span><span>{money(stock.price * 4)}</span><b className={stock.change < 0 ? 'loss' : 'gain'}>{stock.change}%</b></div>)}</div><div className="card table-card"><h3>Allocation</h3><div className="allocation-bar"><i style={{ width: '46%' }} /><i style={{ width: '28%' }} /><i style={{ width: '16%' }} /><i style={{ width: '10%' }} /></div><p className="muted-copy">46% large cap · 28% growth · 16% digital assets · 10% cash</p></div></div></>}
    {active === 'AI Advisor' && <div className="advisor-chat card"><div className="chat-header"><div><div className="ai-pill"><span /> AI Mentor online</div><h3>Ask anything about your strategy.</h3><p>Get explainable guidance on entries, risk, portfolio balance, and your next best move.</p></div><div className="chat-avatar"><Bot /></div></div><div className="chat-suggestions"><button onClick={() => setMentorMessage('How should I manage risk today?')}>Manage today&apos;s risk</button><button onClick={() => setMentorMessage('Explain my portfolio balance')}>Explain my portfolio</button><button onClick={() => setMentorMessage('What should I learn next?')}>What should I learn next?</button></div><div className="chat-transcript"><div className="chat-message ai-message"><div className="chat-avatar small"><Sparkles /></div><p>{mentorReply}</p></div>{mentorMessage && <div className="chat-message user-message"><p>{mentorMessage}</p></div>}</div><div className="chat-composer"><input value={mentorMessage} onChange={e => setMentorMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && !e.nativeEvent.isComposing && submitMentor()} placeholder="Ask your AI advisor..." aria-label="Ask your AI advisor" /><button onClick={submitMentor} aria-label="Send message"><ArrowUpRight /></button></div></div>}
    {active === 'Learn' && <div className="workspace-grid three-up">{[['Beginner', 'Market foundations', 32, 12], ['Intermediate', 'Technical Analysis 101', progress, 12], ['Advanced', 'Strategy engineering', 8, 18]].map(([level, title, done, total]) => <div className="card course-card" key={level as string}><span className="course-level">{level as string}</span><h3>{title as string}</h3><p className="muted-copy">{done}% complete · {Math.round(Number(done) / 100 * Number(total))} of {total} lessons</p><div className="progress-line"><i style={{ width: `${done}%` }} /></div><button className="outline-btn" onClick={() => setProgress(Math.min(100, progress + 8))}>Continue learning <Play /></button></div>)}</div>}
    {active === 'Simulator' && <div className="workspace-grid two-up"><div className="card simulator-card"><div className="card-head"><span>Virtual balance</span><span className="live-status">Paper mode</span></div><strong className="sim-balance">{money(balance)}</strong><Chart compact /><div className="sim-controls"><select value={tradeSymbol} onChange={e => setTradeSymbol(e.target.value)}>{stocks.map(s => <option key={s.symbol}>{s.symbol}</option>)}</select><input type="number" min="1" value={tradeQty} onChange={e => setTradeQty(Number(e.target.value))} /><button className="buy-btn" onClick={() => trade('Buy')}>Buy</button><button className="sell-btn" onClick={() => trade('Sell')}>Sell</button></div><p className="muted-copy">Trading {tradeQty} share of {tradeSymbol}. Actions update your virtual balance only.</p></div><div className="card table-card"><h3>Recent paper trades</h3>{['Bought 2 NVDA', 'Sold 1 TSLA', 'Bought 4 AAPL'].map((item, index) => <div className="data-row" key={item}><span>{item}</span><span>{index + 1}m ago</span><b className="gain">Filled</b></div>)}</div></div>}
    {active === 'Strategies' && <div className="workspace-grid two-up">{[['Momentum Scout', '+24.8%', 'High', 'Uses trend continuation across liquid growth names.'], ['Balanced Core', '+16.2%', 'Medium', 'Blends quality, value, and measured momentum.'], ['Income Shield', '+9.4%', 'Low', 'Prioritizes stability and downside protection.'], ['Crypto Pulse', '+31.6%', 'High', 'Captures digital asset momentum with guardrails.']].map(([name, performance, risk, desc]) => <div className="card strategy-card" key={name}><div className="card-head"><span>{name}</span><span className="strategy-risk">{risk} risk</span></div><strong>{performance}</strong><p>{desc}</p><div className="progress-line"><i style={{ width: `${Number.parseInt(performance) * 2.5}%` }} /></div><button className="outline-btn" onClick={() => setBalance(balance + 100)}>Use strategy <ArrowUpRight /></button></div>)}</div>}
    {active === 'Notifications' && <div className="card notifications-list">{[['Strong buy signal', 'NVDA momentum confidence crossed 90%.', 'Now'], ['Portfolio drift detected', 'Growth allocation is 4% above your target.', '18 min ago'], ['Learning streak', 'You completed 3 lessons this week.', '2 hr ago'], ['Price alert', 'TSLA moved below your watch threshold.', 'Yesterday']].map(([title, text, time], index) => <div className="notification-row" key={title}><div className={`notification-icon ${index === 1 ? 'warning' : ''}`}><Bell /></div><div><strong>{title}</strong><p>{text}</p></div><span>{time}</span></div>)}</div>}
    {active === 'Settings' && <div className="workspace-grid two-up"><div className="card settings-card"><h3>Workspace preferences</h3>{['Market alerts', 'Weekly AI digest', 'Learning reminders', 'Risk warnings'].map((setting, index) => <label className="setting-row" key={setting}><span><strong>{setting}</strong><small>Keep this workspace up to date</small></span><input type="checkbox" defaultChecked={index !== 2} /></label>)}</div><div className="card settings-card"><h3>Account plan</h3><div className="plan-badge">PRO MEMBER</div><strong className="detail-price">AI Strategy Pro</strong><p className="muted-copy">Unlimited simulations, advanced signals, and personalized learning paths.</p><button className="primary-btn" onClick={() => setBalance(balance + 500)}>Manage plan <ArrowUpRight /></button></div></div>}
  </div>
}

export default function Page() {
  const [stocks, setStocks] = useState<any[]>([])
  const [active, setActive] = useState('Dashboard')
  const [collapsed, setCollapsed] = useState(false)
  const [dark, setDark] = useState(true)
  const [currency, setCurrency] = useState('USD')
  const [balance, setBalance] = useState(24850.42)
  const [query, setQuery] = useState('')
  const [progress, setProgress] = useState(68)
  useEffect(() => {
    fetch('https://ai-startegy-judge.onrender.com/api/stocks')
      .then((res) => {
        if (!res.ok) {
          throw new Error(`HTTP error: ${res.status}`)
        }
        return res.json()
      })
      .then((data) => {
        console.log('Stocks received:', data)
        setStocks(data)
      })
      .catch((error) => {
        console.error('Failed to fetch stocks:', error)
      })
  }, [])
  const rate = currency === 'USD' ? 1 : currency === 'EUR' ? 0.92 : 83.1
  const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value * rate)
  const filtered = useMemo(() => stocks.filter(s => `${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase())), [query])
  const taglines: Record<string, string> = { Dashboard: 'Your intelligent edge in every market.', Markets: 'Spot momentum before the crowd does.', Portfolio: 'See where your capital is working hardest.', 'AI Advisor': 'Turn market noise into your next best move.', Learn: 'Build conviction one lesson at a time.', Simulator: 'Practice bold ideas with zero real-world risk.', Strategies: 'Find the playbook that fits your edge.', Notifications: 'Only the signals worth your attention.', Settings: 'Tune your workspace for smarter decisions.' }

  return <div className={dark ? 'app-shell dark' : 'app-shell light'}>
    <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}>
      <div className="brand"><div className="brand-mark"><Sparkles /></div><div className="brand-copy"><strong>AI Strategy</strong><span>JUDGE</span></div><button className="collapse-btn" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle sidebar">{collapsed ? <ChevronRight /> : <ChevronLeft />}</button></div>
      <div className="sidebar-label">Workspace</div>
      <nav>{nav.map(([label, Icon]) => <button key={label} onClick={() => setActive(label)} className={`nav-item ${active === label ? 'active' : ''}`}><Icon /><span>{label}</span>{label === 'Notifications' && <i>3</i>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="learn-mini"><div className="mini-icon"><Zap /></div><div><strong>Daily edge</strong><span>+12.8% this week</span></div></div><div className="user-row"><div className="avatar">AK</div><div className="user-copy"><strong>Alex Kim</strong><span>Pro member</span></div><MoreHorizontal /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu"><Menu /></button><div className="search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search markets, strategies..." /></div><div className="top-actions"><button className="icon-btn" aria-label="Notifications"><Bell /><i>3</i></button><button className="insight-badge"><Sparkles /> AI Insight</button><button className="theme-btn" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun /> : <Moon />}</button><div className="avatar top-avatar">AK</div></div></header>
      <div className="page-wrap">
        <div className="welcome-row"><div><p className="eyebrow"><span className="live-dot" /> MARKET OPEN <span className="muted">/ Friday, Aug 15, 2026</span></p><h1>{active === 'Dashboard' ? 'Good morning, Alex.' : active}</h1><p className="lede">{taglines[active]}</p></div><div className="controls"><select value={currency} onChange={e => setCurrency(e.target.value)} aria-label="Currency"><option>USD</option><option>EUR</option><option>INR</option></select><button className="primary-btn"><Plus /> Add funds</button></div></div>
        {active !== 'Dashboard' ? <WorkspaceView active={active} currency={currency} money={money} balance={balance} setBalance={setBalance} progress={progress} setProgress={setProgress} stocks={stocks} /> : <>
          <section className="hero"><div className="hero-copy"><div className="ai-pill"><span /> Powered by decision intelligence</div><h2>Step Into The<br /><em>Future</em> of Smart Trading</h2><p>AI-optimized strategies with real-time decision intelligence. Make every move with conviction.</p><button className="primary-btn hero-btn" onClick={() => setActive('Simulator')}>Get started <ArrowUpRight /></button><div className="hero-trust"><span>●</span> 24/7 market intelligence <span>●</span> 10k+ strategies analyzed</div></div><div className="hero-visual"><div className="hero-orb"><div className="orb-core"><BrainCircuit /></div></div><div className="float-card market-float"><div className="float-head"><span>Market pulse</span><Activity /></div><strong>+8.42%</strong><Sparkline points="2,16 18,14 34,15 50,8 66,11 82,4 98,6" /></div><div className="float-card signal-float"><div className="float-head"><span>AI signal</span><span className="signal-dot" /></div><strong>Strong Buy</strong><small>NVDA · 94% confidence</small></div></div></section>
          <div className="section-head"><div><p className="eyebrow">OVERVIEW</p><h2>Portfolio at a glance</h2></div><button className="text-btn" onClick={() => setActive('Portfolio')}>View portfolio <ArrowUpRight /></button></div>
          <section className="overview-grid"><div className="card balance-card"><div className="card-head"><span>Total balance</span><button className="more-btn"><MoreHorizontal /></button></div><div className="balance-value">{money(balance)}</div><div className="gain"><ArrowUpRight /> +{money(1842.67)} <span>this month</span></div><Chart /></div><div className="card allocation-card"><div className="card-head"><span>AI confidence score</span><Bot /></div><div className="score-ring"><div><strong>87</strong><span>/100</span></div></div><p>Your portfolio is positioned well for current market conditions.</p><div className="risk-row"><span>Risk level</span><strong>Moderate</strong></div><div className="meter"><i style={{ width: '58%' }} /></div><button className="outline-btn" onClick={() => setActive('AI Advisor')}>Open AI Advisor</button></div></section>
          <section className="content-grid"><div><div className="section-head compact-head"><div><p className="eyebrow">LIVE DATA</p><h2>Market watchlist</h2></div><button className="text-btn" onClick={() => setActive('Markets')}>View all <ArrowUpRight /></button></div><div className="card market-list">{filtered.map(stock => <div className="stock-row" key={stock.symbol}><div className="stock-icon">{stock.symbol[0]}</div><div className="stock-name"><strong>{stock.symbol}</strong><span>{stock.name}</span></div><div className="stock-chart"><Sparkline points={stock.points} red={stock.change < 0} /></div><div className="stock-price"><strong>{stock.symbol === 'BTC' ? '$' + stock.price.toLocaleString() : money(stock.price)}</strong><span className={stock.change < 0 ? 'loss' : 'gain'}>{stock.change > 0 ? '+' : ''}{stock.change}%</span></div></div>)}</div></div><div><div className="section-head compact-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>AI recommendations</h2></div><button className="more-btn"><MoreHorizontal /></button></div><div className="card recommendations">{[['BUY', 'NVDA', 'Momentum remains strong', '94%'], ['HOLD', 'AAPL', 'Healthy consolidation zone', '82%'], ['SELL', 'TSLA', 'Volatility risk elevated', '76%']].map(([type, symbol, text, confidence]) => <div className="recommendation" key={symbol}><div className={`signal-icon ${type.toLowerCase()}`}>{type === 'BUY' ? <ArrowUpRight /> : type === 'SELL' ? <ArrowDownRight /> : <Activity />}</div><div className="recommend-copy"><div><strong>{type}</strong><span>{symbol}</span></div><p>{text}</p></div><b>{confidence}</b></div>)}</div></div></section>
          <section className="learning-strip"><div><p className="eyebrow">BUILD YOUR EDGE</p><h2>Learn. Practice. <em>Earn.</em></h2><p>Sharpen your strategy with AI-guided courses built for every level.</p></div><div className="course-progress"><div className="course-icon"><GraduationCap /></div><div className="course-info"><span>Continue learning</span><strong>Technical Analysis 101</strong><div className="progress-line"><i style={{ width: `${progress}%` }} /></div><small>{progress}% complete · 8 of 12 lessons</small></div><button className="play-btn" onClick={() => setProgress(Math.min(100, progress + 8))}><Play /></button></div></section>
          <section className="feature-grid">{[[BrainCircuit, 'AI Insights', 'See the signal behind the noise.'], [Bell, 'Smart Alerts', 'Never miss a market moment.'], [Coins, 'Auto Investing', 'Put your strategy on autopilot.'], [ShieldCheck, 'Risk Analysis', 'Know your downside before you enter.']].map(([Icon, title, desc]) => <div className="feature-card" key={title as string}><div className="feature-icon"><Icon /></div><strong>{title as string}</strong><p>{desc as string}</p><ArrowUpRight className="feature-arrow" /></div>)}</section>
        </>}
      </div>
    </main>
  </div>
}
